# 服务器前置任务(ubuntu使用)
- name: mongodb
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
  ignore_errors: yes


# 核心任务

- name: mongodb
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - { role: common , tags: "common"}  
    - {role: mongodb, tags: "mongodb"}
    - {role: random, tags: "random"}
    - {role: docker, tags: "docker"}
    - {role: docker_adminmongo, tags: "docker_adminmongo"}




    


                                                                                                    